# Generated by Django 4.2.1 on 2023-10-07 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
