# Generated by Django 4.2.1 on 2023-10-07 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_bid_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_end_time',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='bid_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
