# Generated by Django 4.2.1 on 2023-10-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_bid_end_time_auctionlist_bid_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='bid_end_time',
            field=models.FloatField(verbose_name=0.1),
        ),
    ]
