# Generated by Django 4.2.1 on 2023-10-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlist_bid_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='bid_end_time',
            field=models.FloatField(default=0.001),
        ),
    ]
