# Generated by Django 4.2.1 on 2023-10-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlist_bid_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='daysleft',
            field=models.FloatField(default=0.1),
        ),
    ]
