# Generated by Django 4.2.1 on 2023-10-07 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auctionlist_bid_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
