# Generated by Django 4.2.1 on 2023-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlist_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='created',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='daysleft',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
